### ISSUE TITLE
Remove builder pattern from GenConfig

### ISSUE THREAD

**Issue by kvark** [Osspial/vk-rs#9]
I believe having the user to do this is cleaner and requires less boilerplate:
```rust
    let config = GenConfig {
        remove_type_prefix: true,
        remove_variant_padding: false,
        wrap_bitmasks: false,
        camel_case_variants: false,
        .. GenConfig::new()
    };
```
I think it would also make sense to implement `Default` instead of `new()` method.

**Comment by Osspial** [comment]
`Default` is already implemented - the `new()` method is actually just an alias to `default()`, and I have both implemented because `new()` floats to the top of the documentation page, as it's an inherent impl.

As for removing the builder pattern, I'm not sure if it's necessary. I do think it makes sense to move the documentation for each config option to the actual field and off the method, though.

**Comment by kvark** [comment]
> As for removing the builder pattern, I'm not sure if it's necessary.

My point is that the whole builder pattern here is not necessary. Just a bunch of code that we don't need :)

**Comment by Osspial** [comment]
Fair enough, removed in c84dfdb97d0c6460a822402f75b1d695be7111c3.
